version: "3"
services:
  issuerConn:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.3-rc0
    container_name: sainoforce
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://sainoforce:4001"
      ACAPY_LABEL: "SainoForce"
      ACAPY_LOG_LEVEL: "info"
      ADMIN_PORT: "4000"
      AGENT_PORT: "4001"
    entrypoint: /bin/bash
    command: [
        "-c",
        "aca-py start \
        --admin '0.0.0.0' 4000 \
        --inbound-transport http '0.0.0.0' 4001 \
        --outbound-transport http \
        --seed sainoforce0000000000000000000000  \
        --wallet-type indy \
        --wallet-name issuerwallet \
        --wallet-key issuerkey \
        --image-url 'https://media.licdn.com/dms/image/C560BAQF-R8nfYe-NuQ/company-logo_200_200/0/1644986277006?e=2147483647&v=beta&t=dyUn20rdfCwj0Au4bfIrPb1l3ehAMNxD1xtpWq2mnLc' \
        --auto-provision \
        --auto-accept-invites \
        --auto-accept-requests \
        --genesis-url 'https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis' \
        --auto-ping-connection \
        --tails-server-base-url 'https://e8bb-210-195-159-76.ngrok.io/' ",
      ]
    ports:
      - "4000:4000"
      - "4001:4001"
  angularconn:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
